#!/usr/bin/env node
/**
 * Real `dsh --profile headless --json` run against a mock model route.
 *
 * This is the one surface the unit tests and the composition smoke cannot
 * reach: the actual launcher, its newline-delimited JSON stdout contract, and
 * the plugin's metering while an agent loop runs. It asserts the properties a
 * line-oriented supervisor depends on:
 *
 *   1. every stdout line is a well-formed JSON event, so nothing the plugin
 *      does pollutes the machine-readable stream;
 *   2. the stream opens with `session` and reports the identity the run used;
 *   3. the ledger records that identity, once per run, and a second run that
 *      adopts the same session adds its own fact instead of duplicating one.
 *
 * Everything happens in a throwaway DSH home: the profile, the ledger, and the
 * session log are written there and removed at the end. The home's
 * `profiles/node_modules` is a link to the real one, so the bundles resolve
 * without installing anything and without a network call.
 *
 * Needs `dsh` on PATH; without it the script reports SKIP and exits zero. Pass
 * `--require-dsh` (or set DSH_REQUIRE_HEADLESS=1) to make that a failure.
 *
 * @module dsh-provider-openai-subscription/scripts/headless-smoke
 */

import { spawnSync } from 'node:child_process'
import { existsSync } from 'node:fs'
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { MOCK_MODEL, MOCK_PROVIDER, MOCK_TEXT } from './headless-mock-provider.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const bundlePatch = join(root, 'cordis.patch.yml')

/** Release mode: a skipped check is a failed check. */
const REQUIRE_DSH = process.argv.includes('--require-dsh') || process.env.DSH_REQUIRE_HEADLESS === '1'
const keep = process.argv.includes('--keep')

/** Report a check that could not run. */
function skip(message) {
  if (REQUIRE_DSH) {
    console.error(`FAIL: ${message} (--require-dsh refuses to skip)`)
    process.exit(1)
  }
  console.log(`SKIP: ${message}`)
  process.exit(0)
}

function fail(message) {
  console.error(`FAIL: ${message}`)
  process.exitCode = 1
}

function ok(message) {
  console.log(`OK: ${message}`)
}

const probe = spawnSync('dsh --version', { shell: true, encoding: 'utf8' })
if (probe.error !== undefined || probe.status !== 0) {
  skip('dsh is not available on PATH')
}

// The real install supplies the bundles and the harness packages this run
// composes; the smoke only borrows them.
const realHome = process.env.DSH_HOME
if (realHome === undefined || realHome.length === 0) {
  skip('DSH_HOME is not set, so there is no installed harness to borrow')
}
const realModules = join(realHome, 'profiles', 'node_modules')
if (!existsSync(join(realModules, '@deepseek-ai', 'dsh', 'package.json'))) {
  skip(`no installed harness under ${realModules}`)
}

const home = await mkdtemp(join(tmpdir(), 'dsh-openai-subscription-headless-'))
const profile = 'headless-smoke'
const profileDir = join(home, 'profiles', profile)
const ledgerPath = join(home, 'storages', 'openai-subscription-meter', 'usage.json')

/** The row this plugin contributes, inserted by absolute path. */
const pluginRow = `    - id: llm-openai-subscription
      name: '${resolve(root, 'src', 'index.js').split('\\').join('/')}'
      config:
        state: active
        oauth:
          clientId: headless-smoke
`

try {
  await mkdir(profileDir, { recursive: true })
  await symlink(realModules, join(home, 'profiles', 'node_modules'), process.platform === 'win32' ? 'junction' : 'dir')
  await writeFile(join(profileDir, 'package.json'), JSON.stringify({
    name: `dsh-profile-${profile}`,
    private: true,
    dependencies: {},
    dsh: { profile: { bundles: ['@deepseek-ai/dsh-base', '@deepseek-ai/dsh-headless'], patchReload: 'startup' } },
  }, null, 2))

  // The mock route, this plugin's row, and the default model selection that
  // points the agent at the mock.
  await writeFile(join(profileDir, 'cordis.patch.yml'), [
    '# Generated by scripts/headless-smoke.mjs; not a shipped composition.',
    '- insert:',
    `    - id: headless-mock-provider`,
    `      name: '${join(here, 'headless-mock-provider.mjs').split('\\').join('/')}'`,
    pluginRow.replace(/\n$/, ''),
    '- id: agent-default-model',
    '  config:',
    `    provider: ${MOCK_PROVIDER}`,
    `    model: ${MOCK_MODEL}`,
    '',
  ].join('\n'))

  console.log(`temp DSH home: ${home}`)

  /**
   * Run one headless task and return the parsed event stream.
   * @param {string} task - the positional task.
   * @param {string} [sessionId] - adopt this Session instead of a fresh one.
   * @returns {{status: number|null, events: object[], stdout: string, stderr: string}}
   */
  function run(task, sessionId) {
    const command = [
      'dsh',
      `--profile ${profile}`,
      '--json',
      ...(sessionId === undefined ? [] : [`--session-id ${sessionId}`]),
      JSON.stringify(task),
    ].join(' ')
    const result = spawnSync(command, {
      shell: true,
      encoding: 'utf8',
      cwd: root,
      env: { ...process.env, DSH_HOME: home },
    })
    const stdout = result.stdout ?? ''
    const lines = stdout.split('\n').filter((line) => line.trim().length > 0)
    const events = []
    for (const [index, line] of lines.entries()) {
      try {
        events.push(JSON.parse(line))
      } catch {
        events.push({ __unparsable: line, __line: index + 1 })
      }
    }
    return { status: result.status, events, stdout, stderr: result.stderr ?? '' }
  }

  /** Read the ledger, tolerating its debounced write. */
  async function readLedger() {
    for (let attempt = 0; attempt < 80; attempt += 1) {
      try {
        const parsed = JSON.parse(await readFile(ledgerPath, 'utf8'))
        if (Array.isArray(parsed.entries)) return parsed.entries
      } catch {
        // Not written yet.
      }
      await new Promise((resolveWait) => { setTimeout(resolveWait, 100) })
    }
    return undefined
  }

  /**
   * The facts one session owns, split by whether they answered the task or the
   * auxiliary title call, which is a real model call the meter also records.
   * @param {object[]|undefined} entries
   * @param {unknown} sessionId
   * @returns {{all: object[], task: object[]}}
   */
  function factsFor(entries, sessionId) {
    const all = (entries ?? []).filter((entry) => entry.fact?.sessionId === sessionId)
    return { all, task: all.filter((entry) => entry.fact.purpose === undefined) }
  }

  // ── run 1: a fresh session ──────────────────────────────────────────────
  const first = run('say hi')
  if (first.status !== 0) {
    fail(`headless exited ${String(first.status)}; stderr: ${first.stderr.trim().split('\n').slice(-6).join(' | ')}`)
  } else {
    const unparsable = first.events.filter((event) => event.__unparsable !== undefined)
    if (unparsable.length > 0) {
      fail(`stdout carried ${unparsable.length} non-JSON line(s); first: ${JSON.stringify(unparsable[0].__unparsable)}`)
    } else {
      ok(`every stdout line is a JSON event (${first.events.length} events)`)
    }
    if (first.events[0]?.type !== 'session' || typeof first.events[0].sessionId !== 'string') {
      fail(`the stream must open with a session event, got ${JSON.stringify(first.events[0])}`)
    }
    if (first.events.at(-1)?.type !== 'final') {
      fail(`the stream must close with final, got ${JSON.stringify(first.events.at(-1))}`)
    }
    const text = first.events.filter((event) => event.type === 'text').map((event) => event.text).join('')
    if (!text.includes(MOCK_TEXT)) {
      fail(`the run did not deliver the mock answer; text events: ${JSON.stringify(text)}`)
    } else {
      ok('the run delivered the mock answer through the real agent loop')
    }
  }

  const sessionId = first.events[0]?.sessionId
  const entries = await readLedger()
  if (entries === undefined) {
    fail(`the meter never wrote a ledger at ${ledgerPath}`)
  } else {
    const { all, task } = factsFor(entries, sessionId)
    if (task.length !== 1) {
      fail(`the ledger must record exactly one task call for the headless session, got ${task.length} (${all.length} facts total)`)
    } else if (all.some((entry) => entry.fact.provider !== MOCK_PROVIDER)) {
      fail(`a recorded fact names ${String(all.find((entry) => entry.fact.provider !== MOCK_PROVIDER).fact.provider)}, expected ${MOCK_PROVIDER}`)
    } else {
      ok(`the ledger recorded the headless session through the auto-provider path (${all.length} facts: ${task.length} task, ${all.length - task.length} auxiliary)`)
    }

    // ── run 2: adopt the same session ─────────────────────────────────────
    if (typeof sessionId === 'string') {
      const second = run('say hi again', sessionId)
      if (second.status !== 0) {
        fail(`the resuming run exited ${String(second.status)}; stderr: ${second.stderr.trim().split('\n').slice(-6).join(' | ')}`)
      } else if (second.events.some((event) => event.__unparsable !== undefined)) {
        fail('the resuming run polluted stdout')
      } else if (second.events[0]?.sessionId !== sessionId) {
        fail(`the resuming run reported ${String(second.events[0]?.sessionId)}, expected ${sessionId}`)
      } else {
        const after = await readLedger()
        const adopted = factsFor(after, sessionId)
        const callIds = new Set(adopted.all.map((entry) => entry.fact.callId))
        if (adopted.task.length !== 2) {
          fail(`two runs must record two task calls for the session, got ${adopted.task.length}`)
        } else if (callIds.size !== adopted.all.length) {
          fail(`every recorded call must be distinct, got ${callIds.size} ids for ${adopted.all.length} facts`)
        } else if (adopted.all.some((entry) => entry.fact.provider !== MOCK_PROVIDER)) {
          fail('the adopted session recorded a fact from another provider')
        } else {
          ok('a second run adopting the same session adds its own call instead of duplicating one')
        }
      }
    }
  }

  if (process.exitCode === undefined || process.exitCode === 0) {
    console.log('headless smoke: PASS')
  } else {
    console.log('headless smoke: FAIL')
  }
} finally {
  if (keep) console.log(`kept: ${home}`)
  else await rm(home, { recursive: true, force: true })
}
